version: "3.7"

services:
  web:
    build: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - web/.env
    depends_on:
      - bot

  db:
    image: postgres:12.0-alpine
    user: ${user}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
      - ./data/pg-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_passwd}
      - POSTGRES_DB=${db_name}
      - POSTGRES_MULTIPLE_DATABASES=Stocks

  bot:
    build: bot
    command: python bot_server.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8060:8060

volumes:
  postgres_data:
