version: '3.7'

services:
  web:
    build: .
    command: python stockytron/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_passwd}
      - POSTGRES_DB=${db_name}

volumes:
  postgres_data:
