# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bot_pb2 as bot__pb2


class StockBotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStock = channel.unary_unary(
                '/StockBot/GetStock',
                request_serializer=bot__pb2.StockRequest.SerializeToString,
                response_deserializer=bot__pb2.Stock.FromString,
                )


class StockBotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStock,
                    request_deserializer=bot__pb2.StockRequest.FromString,
                    response_serializer=bot__pb2.Stock.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StockBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockBot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StockBot/GetStock',
            bot__pb2.StockRequest.SerializeToString,
            bot__pb2.Stock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
